trigger:
- master

jobs:
  - job: build_web
    displayName: Build Jellyfin-web
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        clean: true
        submodules: true
        persistCredentials: true
      - task: CmdLine@2
        displayName: Check out Jellyfin Web
        inputs:
          script: |
            git clone --single-branch --branch master --depth=1 https://github.com/jellyfin/jellyfin-web.git $(Agent.TempDirectory)/jellyfin-web
      - task: UseNode@1
        displayName: Install Node
        inputs:
          version: '12.x'
      - task: CmdLine@2
        displayName: Install Jellyfin Web
        inputs:
          script: |
            yarn install
          workingDirectory: $(Agent.TempDirectory)/jellyfin-web
          failOnStderr: false

      - task: CmdLine@2
        displayName: Install Jellyfin Tizen
        inputs:
          script: | 
            JELLYFIN_WEB_DIR=$(Agent.TempDirectory)/jellyfin-web/dist yarn install
          failOnStderr: false

      - task: CmdLine@2
        displayName: Setup Tizen Studio
        inputs:
          script: | 
            export TIZEN_HOME=$(Agent.TempDirectory)/tizen/
            export TIZEN_CLI_INSTALLER_URL=http://download.tizen.org/sdk/Installer/tizen-studio_3.7/web-cli_Tizen_Studio_3.7_ubuntu-64.bin
            export TIZEN_STUDIO=$TIZEN_HOME/tizen-studio

            echo 'deb http://deb.debian.org/debian jessie main' >> /etc/apt/sources.list \
              && apt-get update \
              && apt-get -y install curl libssl1.0.0 \
              && rm -rf /var/lib/apt/lists/*
            
            cd $TIZEN_HOME

            INSTALLER=$(Agent.TempDirectory)/$(basename "$TIZEN_CLI_INSTALLER_URL") \
              && curl "$TIZEN_CLI_INSTALLER_URL" > "$INSTALLER" \
              && chmod 755 "$INSTALLER" \
              && "$INSTALLER" --no-java-check --accept-license $TIZEN_STUDIO \
              && rm "$INSTALLER" \
              && cd $TIZEN_STUDIO/tools/certificate-generator/patches/partner \
              && ./patch.sh $TIZEN_STUDIO \
              && rm -rf \
                $TIZEN_HOME/.package-manager \
                $TIZEN_HOME/tizen-studio/license \
                $TIZEN_HOME/tizen-studio/package-manager
          failOnStderr: false

 